/**
 *  Autogenerated Entrypoint  
 *  DO NOT MODIFY
 */
 
import path from 'path';
const currentPath = process.cwd();

export default {
    entry: {
        eureka: [
            path.join(currentPath, '/src/styles/colorschemes/eureka.scss'),
			path.join(currentPath, 'node_modules/@caweb/icon-library/build/font-only.css'),
			path.join(currentPath, '/src/scripts/index.js'),
            
        ]
    }
};
    