/**
 *  Autogenerated Entrypoint  
 *  DO NOT MODIFY
 */
 
export default {
    entry: {
        mono: [
            'C:/Development/CAWebPublishing/framework/src/styles/colorschemes/mono.scss',
			'C:/Development/CAWebPublishing/framework/src/scripts/index.js'
        ]
    },
    output: {
        clean: false
    }
};
    