/**
 *  Autogenerated Entrypoint  
 *  DO NOT MODIFY
 */
 
export default {
    entry: {
        santacruz: [
            '@caweb/icon-library',
            'C:/Development/CAWebPublishing/framework/src/styles/colorschemes/santacruz.scss',
			'C:/Development/CAWebPublishing/framework/src/scripts/index.js'
        ]
    },
    output: {
        clean: false
    }
};
    