/**
 *  Autogenerated Entrypoint  
 *  DO NOT MODIFY
 */
 
export default {
    entry: {
        shasta: [
            '@caweb/icon-library',
            '/src/styles/colorschemes/shasta.scss',
			'/src/scripts/index.js'
        ]
    },
    output: {
        clean: false
    }
};
    